### ISSUE TITLE
Vertically align text in the center of a container

### ISSUE THREAD

**Issue by wenqili** [wenqili/knowtebook#12]
```css
.vertical-center-align {
    display: flex;
    align-items: center; // Applies to flex containers.
    justify-content: center;
}
```
